bindings:
  - id: uer1li907z85blct
    name: api-redis
    properties: {}
    source:
      kind: http
      properties:
        methods: post
        path: /redis
    target:
      kind: kubemq.query
      properties:
        address: localhost:50000
        channel: redis
  - id: uer1li907z85blct
    name: api-postgres
    properties: {
       log_level: debug
    }
    source:
      kind: http
      properties:
        methods: post
        path: /*
    target:
      kind: kubemq.query
      properties:
        address: localhost:50000
        channel: postgres
  - id: uer1li907z85blct
    name: api-elastic
    properties: {}
    source:
      kind: http
      properties:
        methods: post
        path: /elastic
    target:
      kind: kubemq.query
      properties:
        address: localhost:50000
        channel: elastic
