apiPort: 8082
logLevel: debug
bindings:
- name: fs
  source:
    kind: storage.filesystem
    properties:
      folders: 'd:\test\source-fs,d:\test\source-fs2'
      bucket_type: minio
      bucket_name: bucket2
      concurrency: 5
  target:
    kind: kubemq.queue
    properties:
      address: localhost:50000
      channel: queue.fs
  properties: {}

