apiPort: 8082
bindings:
- name: fs
  source:
    kind: storage.filesystem
    properties:
      root: 'd:\test\source-fs'
      bucket_type: filesystem
      bucket_name: bucket
      concurrency: 5
  target:
    kind: kubemq.queue
    properties:
      address: localhost:50000
      channel: queue.fs
  properties: {}
