bindings:
  - name: minio
    source:
      kind: storage.minio
      properties:
        endpoint: "localhost:9000"
        use_ssl: "false"
        access_key_id: "minio"
        secret_access_key: "minio123"
        folders: '/'
        target_type: filesystem
        bucket_name: bucket2
        concurrency: 5
        scan_interval: 2
    target:
      kind: kubemq.queue
      properties:
        address: localhost:50000
        channel: queue.minio
    properties: {}
