bindings:
  - name: s3
    source:
      kind: aws.s3
      properties:

        region: "us-east-1"
        token: ""
        folders: '/'
        target_type: filesystem
        bucket_name: bucket2
        concurrency: 5
        scan_interval: 2
    target:
      kind: kubemq.queue
      properties:
        address: localhost:50000
        channel: queue.minio
    properties: {}
