apiPort: 8081
bindings:
- name: source-1
  properties: {}
  source:
    kind: storage.filesystem
    properties:
      bucket_name: kubemq-targets
      bucket_type: aws
      folders: e:\demo\s3
      backup_folder: e:\demo\backup\dir1\dir2
  target:
    kind: kubemq.queue
    properties:
      address: localhost:50000
      channel: s3
logLevel: ""
