apiPort: 0
bindings:
- name: source-1
  properties: {}
  source:
    kind: http
    properties:
      methods: post
      path: /*
  target:
    kind: kubemq.queue
    properties:
      address: kubemq-cluster-grpc.kubemq:50000
      channel: q1
logLevel: ""
